/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--ds-font-sans)", "'Plus Jakarta Sans'", "system-ui", "sans-serif"],
        mono: ["var(--ds-font-mono)", "'DM Mono'", "monospace"],
        serif: ["var(--ds-font-serif)", "'Source Serif 4'", "Georgia", "serif"],
      },
      colors: {
        blue: "var(--blue)",
        "blue-dim": "var(--blue-dim)",
        cloud: {
          dark: "var(--cloud-dark)",
          mid: "var(--cloud-mid)",
          light: "var(--cloud-light)",
          edge: "var(--cloud-edge)",
        },
        /* Semantic design-system tokens */
        ds: {
          page: "var(--ds-background-page)",
          surface: "var(--ds-background-surface)",
          subtle: "var(--ds-background-subtle)",
          inverse: "var(--ds-background-inverse)",
          "text-primary": "var(--ds-text-primary)",
          "text-secondary": "var(--ds-text-secondary)",
          "text-muted": "var(--ds-text-muted)",
          "text-inverse": "var(--ds-text-inverse)",
          "text-inverse-muted": "var(--ds-text-inverse-muted)",
          border: "var(--ds-border-default)",
          "border-strong": "var(--ds-border-strong)",
          primary: "var(--ds-action-primary)",
          "primary-hover": "var(--ds-action-primary-hover)",
          "primary-soft": "var(--ds-action-primary-soft)",
          "primary-border": "var(--ds-action-primary-border)",
          navy: "var(--ds-action-navy)",
          "navy-hover": "var(--ds-action-navy-hover)",
          teal: "var(--ds-action-teal)",
          "teal-soft": "var(--ds-action-teal-soft)",
          destructive: "var(--ds-action-destructive)",
          "destructive-soft": "var(--ds-action-destructive-soft)",
          success: "var(--ds-status-success-text)",
          "success-bg": "var(--ds-status-success-background)",
          "success-border": "var(--ds-status-success-border)",
          warning: "var(--ds-status-warning-text)",
          "warning-bg": "var(--ds-status-warning-background)",
          "warning-border": "var(--ds-status-warning-border)",
          critical: "var(--ds-status-critical-text)",
          "critical-bg": "var(--ds-status-critical-background)",
          "critical-border": "var(--ds-status-critical-border)",
          info: "var(--ds-status-info-text)",
          "info-bg": "var(--ds-status-info-background)",
          "info-border": "var(--ds-status-info-border)",
          unknown: "var(--ds-status-unknown-text)",
          "unknown-bg": "var(--ds-status-unknown-background)",
          "unknown-border": "var(--ds-status-unknown-border)",
          ai: "var(--ds-ai-background)",
          "ai-border": "var(--ds-ai-border)",
          "ai-heading": "var(--ds-ai-heading)",
          "ai-text": "var(--ds-ai-text)",
          /* Legacy aliases used by existing ui/* components */
          paper: {
            surface: "var(--ds-background-surface)",
            muted: "var(--ds-background-subtle)",
            line: "var(--ds-border-default)",
          },
        },
        paper: {
          surface: "var(--ds-background-surface)",
          muted: "var(--ds-background-subtle)",
          line: "var(--ds-border-default)",
        },
        ink: {
          DEFAULT: "var(--ds-text-primary)",
          mid: "var(--ds-text-secondary)",
          dim: "var(--ds-text-muted)",
        },
        legal: {
          accent: "var(--ds-action-primary)",
          soft: "var(--ds-action-primary-soft)",
          ok: "var(--ds-status-success-text)",
          okBg: "var(--ds-status-success-background)",
          warn: "var(--ds-status-warning-text)",
          warnBg: "var(--ds-status-warning-background)",
          risk: "var(--ds-status-critical-text)",
          riskBg: "var(--ds-status-critical-background)",
        },
      },
      borderRadius: {
        ds: "var(--ds-radius-md)",
        "ds-sm": "var(--ds-radius-sm)",
        "ds-lg": "var(--ds-radius-lg)",
        "ds-xl": "var(--ds-radius-xl)",
      },
      boxShadow: {
        card: "var(--ds-shadow-none)",
        "ds-sm": "var(--ds-shadow-sm)",
        "ds-md": "var(--ds-shadow-md)",
        "ds-lg": "var(--ds-shadow-lg)",
        "ds-focus": "var(--ds-focus-ring)",
      },
      spacing: {
        "sidebar": "var(--ds-sidebar-width)",
        "header": "var(--ds-header-height)",
      },
      maxWidth: {
        reading: "var(--ds-reading-max)",
        content: "var(--ds-content-max)",
      },
      zIndex: {
        sticky: "var(--ds-z-sticky)",
        dropdown: "var(--ds-z-dropdown)",
        drawer: "var(--ds-z-drawer)",
        modal: "var(--ds-z-modal)",
        toast: "var(--ds-z-toast)",
      },
      transitionDuration: {
        fast: "var(--ds-duration-fast)",
        normal: "var(--ds-duration-normal)",
        slow: "var(--ds-duration-slow)",
      },
    },
  },
  plugins: [],
};
